# -*- coding: utf-8 -*-
"""Caso_Videojuegos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BYfsaiHePIwZ1xT1VwOUS5URrAlFAAh2

#Diccionario de datos

- Rank: Ranking of overall sales

- Name: The games name

- Platform: Platform of the games release (i.e. PC,PS4, etc.)

- Year: Year of the game's release

- Genre: Genre of the game

- Publisher: Publisher of the game

- NA_Sales: Sales in North America (in millions)

- EU_Sales: Sales in Europe (in millions)

- JP_Sales: Sales in Japan (in millions)

- Other_Sales: Sales in the rest of the world (in millions)

- Global_Sales: Total worldwide sales.

#Importando Librerias
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
from google.colab import drive

"""#Importando DataSet desde GDrive"""

drive.mount('/content/drive')

rutaVG = "/content/drive/MyDrive/mae_lucho/Proy_inv/videojuegos/vgsales.csv"
dataVG = pd.read_csv(rutaVG)

"""#Explorando DataSet VG Sales"""

print("Filas y columnas (r,c):",dataVG.shape,"\n")
dataVG.head()

dataVG.tail()

dataVG.info()

"""#Explorando valores nulos del DataSet"""

print("Valores Faltantes")
print(dataVG.isnull().sum())
print("\nValores Faltantes %")
print(dataVG.isnull().mean().round(3)*100)

dataVGC=dataVG.dropna()
dataVGC.info()

nullYears=pd.to_datetime(dataVGC['Year'],errors='coerce').isnull().sum()
print("Cantidad de filas con años nulos:",nullYears)

"""# Explorando Outliers del DataSet"""

dataVGC.describe().round(2)

colNum = ['Rank','Year','NA_Sales','EU_Sales','JP_Sales','Other_Sales','Global_Sales']

for i, col in enumerate(colNum):
  fig=px.scatter(dataVGC,y=col,width=1000,height=250)

  # Ajustar márgenes (arriba, derecha, abajo, izquierda)
  fig.update_layout(margin=dict(t=30, r=30, b=30, l=40))
  fig.show()

# Configuración
colCat = ['Platform','Genre','Publisher']
valor_comparacion = 'JP_Sales'  # Cambia por la columna que quieras comparar

def plot_top10_comparison(df, category_col, value_col, top_n=20):
    # 1. Agrupar y calcular la suma del valor de comparación
    grouped = df.groupby(category_col)[value_col].sum().reset_index()
    grouped.columns = [category_col, 'Total']

    # 2. Ordenar y seleccionar Top 10
    top_data = grouped.sort_values('Total', ascending=False).head(top_n)
    others_total = grouped.sort_values('Total', ascending=False)['Total'][top_n:].sum()

    # 3. Agregar fila "Otros"
    if others_total > 0:
        others_row = pd.DataFrame({category_col: ['Otros'], 'Total': [others_total]})
        plot_data = pd.concat([top_data, others_row])
    else:
        plot_data = top_data

    # 4. Crear gráfico
    fig = px.bar(plot_data,
                 x=category_col,
                 y='Total',
                 title=f'Top {top_n} {category_col} por {value_col} vs Otros',
                 color=category_col,
                 text='Total',
                 labels={'Total': f'Total {value_col}'})

    # 5. Personalizar
    fig.update_layout(
        xaxis_title=None,
        xaxis={'categoryorder': 'total descending'},
        hovermode="x unified",
        showlegend=False
    )

    fig.update_traces(
        texttemplate='%{y:,.1f}',
        textposition='outside',
        hovertemplate=f"<b>%{{x}}</b><br>{value_col}: %{{y:,.1f}}"
    )

    fig.show()

# Generar gráficos para cada categoría
for category in colCat:
    plot_top10_comparison(dataVGC, category, valor_comparacion)

import pandas as pd

# Lista de columnas de ventas regionales (ajústala si tus nombres difieren)
region_cols = ['NA_Sales', 'EU_Sales', 'JP_Sales', 'Other_Sales']

# 1️⃣ Región que más aporta a las ventas globales
dataVGC['Region_Mayor_Venta'] = dataVGC[region_cols].idxmax(axis=1)

# 2️⃣ % que representa esa región sobre el total global
dataVGC['Pct_Mayor_Venta'] = (
    dataVGC[region_cols].max(axis=1)             # venta más alta entre las regiones
    .div(dataVGC['Global_Sales'])               # / ventas globales
    .mul(100)                                   # → porcentaje
    .round(2)                                   # redondeo a 2 decimales
)



dataVGC.head(1000)

dataVGC.head(1000)

import pandas as pd
import matplotlib.pyplot as plt

dataVGC = pd.read_csv('/content/drive/MyDrive/mae_lucho/Proy_inv/videojuegos/vgsales.csv')

# 1. Sumar ventas globales por género
genre_sales = (
    dataVGC.groupby('Genre')['Global_Sales']
           .sum()
           .sort_values(ascending=False)
)

# 2. Gráfico de barras + etiquetas de valor
plt.figure(figsize=(10, 6))
ax = genre_sales.plot(kind='bar')

# Añadir los valores encima de cada barra
for p in ax.patches:
    ax.annotate(f'{p.get_height():.1f}',                # 1 decimal
                (p.get_x() + p.get_width() / 2,        # posición X (centro)
                 p.get_height()),                      # posición Y (top)
                ha='center', va='bottom', fontsize=9)

plt.xlabel('Género')
plt.ylabel('Ventas globales (millones)')
plt.title('Ventas globales por género de videojuegos')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv('/content/drive/MyDrive/mae_lucho/Proy_inv/videojuegos/vgsales.csv')  # o /mnt/data/vgsales.csv

ventas = (df.dropna(subset=['Year'])
            .assign(Year=lambda d: d['Year'].astype(int))
            .groupby('Year')['Global_Sales']
            .sum()
            .sort_index())

fig, ax = plt.subplots(figsize=(14, 6))
ax.plot(ventas.index, ventas.values, marker='o', linewidth=2, color='#1f77b4')

for x, y in ventas.items():
    ax.annotate(f'{y:.1f}',
                xy=(x, y), xytext=(0, 6),
                textcoords='offset points',
                ha='center', va='bottom', fontsize=8,
                bbox=dict(boxstyle='round,pad=0.15',
                          fc='white', alpha=0.7, ec='none'))

ax.set_xlabel('Año')
ax.set_ylabel('Ventas globales (millones)')
ax.set_title('Ventas globales por año')
ax.grid(True, linestyle='--', alpha=0.3)
plt.tight_layout()
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

# 1) Leer el CSV (ajusta la ruta si trabajas en Colab)
df = pd.read_csv('/content/drive/MyDrive/mae_lucho/Proy_inv/videojuegos/vgsales.csv')

# 2) Región que quieres analizar
region = 'EU_Sales'            # o 'NA_Sales', 'JP_Sales', 'Other_Sales'

# 3) Preparar datos (quitar nulos)
sub = df[[region, 'Global_Sales']].dropna()

# 4) Correlación y línea de tendencia (para dar contexto)
corr = sub[region].corr(sub['Global_Sales'])
m, b = np.polyfit(sub[region], sub['Global_Sales'], 1)

# 5) Scatter plot mejorado
plt.figure(figsize=(8, 6))
plt.scatter(sub[region], sub['Global_Sales'], s=30, alpha=0.5)

# Línea de tendencia
x_vals = np.linspace(sub[region].min(), sub[region].max(), 100)
plt.plot(x_vals, m * x_vals + b, linestyle='--', label=f'Tendencia (R = {corr:.2f})')

# Etiquetas y estilo
plt.xlabel(f'Ventas en {region.split("_")[0]} (millones)')
plt.ylabel('Ventas globales (millones)')
plt.title(f'Relación entre ventas en {region.split("_")[0]} y ventas globales')
plt.grid(True, linestyle='--', alpha=0.3)
plt.legend()
plt.tight_layout()
plt.show()

"""# "El género de los videojuegos influye significativamente en las ventas globales."
"""

import pandas as pd
import matplotlib.pyplot as plt

dataVGC = pd.read_csv('/content/drive/MyDrive/mae_lucho/Proy_inv/videojuegos/vgsales.csv')

# 1. Sumar ventas globales por género
genre_sales = (
    dataVGC.groupby('Genre')['Global_Sales']
           .sum()
           .sort_values(ascending=False)
)

# 2. Gráfico de barras + etiquetas de valor
plt.figure(figsize=(10, 6))
ax = genre_sales.plot(kind='bar')

# Añadir los valores encima de cada barra
for p in ax.patches:
    ax.annotate(f'{p.get_height():.1f}',                # 1 decimal
                (p.get_x() + p.get_width() / 2,        # posición X (centro)
                 p.get_height()),                      # posición Y (top)
                ha='center', va='bottom', fontsize=9)

plt.xlabel('Género')
plt.ylabel('Ventas globales (millones)')
plt.title('Ventas globales por género de videojuegos')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

"""# "Las plataformas más populares tienen un impacto notable en las ventas regionales."

"""

import pandas as pd
import matplotlib.pyplot as plt

# 1) Leer CSV (ajusta la ruta si estás en Colab)
df = pd.read_csv('/content/drive/MyDrive/mae_lucho/Proy_inv/videojuegos/vgsales.csv')

# 2) Columnas de ventas regionales
regiones = ['NA_Sales', 'EU_Sales', 'JP_Sales', 'Other_Sales']

# 3) Agregar ventas por plataforma y región
plat_sales = (
    df.groupby('Platform')[regiones + ['Global_Sales']]
      .sum()
      .sort_values('Global_Sales', ascending=False)
)

# 4) Seis plataformas más populares
top_platforms = plat_sales.head(6)

# 5) Gráfico de barras apiladas
fig, ax = plt.subplots(figsize=(10, 6))
top_platforms[regiones].plot(kind='bar', stacked=True, width=0.7, ax=ax)

# 6) Etiquetas de valor en cada segmento y total arriba
for i, plataforma in enumerate(top_platforms.index):
    total = 0
    for reg in regiones:
        value = top_platforms.loc[plataforma, reg]
        # Altura acumulada para colocar texto en el centro de cada segmento
        y_center = total + value / 2
        if value > 0:
            ax.text(i, y_center, f'{value:.0f}',
                    ha='center', va='center', fontsize=8, color='white')
        total += value
    # Etiqueta del total arriba de la barra
    ax.text(i, total + 10, f'{total:.0f}',
            ha='center', va='bottom', fontsize=9, fontweight='bold')

# 7) Estilo
ax.set_xlabel('Plataforma')
ax.set_ylabel('Ventas regionales (millones)')
ax.set_title('Impacto regional en las plataformas más populares')
ax.legend(title='Región')
plt.tight_layout()
plt.show()

import pandas as pd
import matplotlib.pyplot as plt

# ── 1. Leer el CSV ──────────────────────────────────────────────
df = pd.read_csv('/content/drive/MyDrive/mae_lucho/Proy_inv/videojuegos/vgsales.csv')
     # ajusta la ruta si es necesario

# ── 2. Seleccionar columnas numéricas para el análisis ─────────
cols = ['NA_Sales', 'EU_Sales', 'JP_Sales', 'Other_Sales', 'Global_Sales']
data = df[cols].dropna()

# ── 3. Matriz de correlación (Pearson) ─────────────────────────
corr_matrix = data.corr(method='pearson').round(2)
print("\nMatriz de correlaciones (Pearson):\n")
print(corr_matrix)

# ── 4. Heatmap simple con matplotlib ───────────────────────────
plt.figure(figsize=(6, 5))
plt.imshow(corr_matrix, cmap='coolwarm', vmin=-1, vmax=1)
plt.colorbar(label='Coeficiente de correlación')
plt.xticks(range(len(cols)), cols, rotation=45, ha='right')
plt.yticks(range(len(cols)), cols)
plt.title('Heatmap de correlaciones')
plt.tight_layout()
plt.show()